

export const Types = {
  GET_DISH_DETAIL_REQUEST: 'dish/GET_DISH_DETAIL_REQUEST',
  GET_DISH_DETAIL_SUCCESS: 'dish/GET_DISH_DETAIL_SUCCESS',
  GET_DISH_DETAIL_FAILURE: 'dish/GET_DISH_DETAIL_FAILURE',
  GET_ALL_DISHES_REQUEST: 'dish/GET_ALL_DISHES_REQUEST',
  GET_ALL_DISHES_SUCCESS: 'dish/GET_ALL_DISHES_SUCCESS',
  GET_ALL_DISHES_FAILURE: 'dish/GET_ALL_DISHES_FAILURE',
  CREATE_DISH_REQUEST: 'dish/CREATE_DISH_REQUEST',
  CREATE_DISH_SUCCESS: 'dish/CREATE_DISH_SUCCESS',
  CREATE_DISH_FAILURE: 'dish/CREATE_DISH_FAILURE',
};
