export const Types = {
  GET_ALL_EVENTS_REQUEST: 'events/GET_ALL_EVENTS_REQUEST',
  GET_ALL_EVENTS_SUCCESS: 'events/GET_ALL_EVENTS_SUCCESS',
  GET_ALL_EVENTS_FAILURE: 'events/GET_ALL_EVENTS_FAILURE',
  GET_EVENT_DETAILS_REQUEST: 'events/GET_EVENT_DETAILS_REQUEST',
  GET_EVENT_DETAILS_SUCCESS: 'events/GET_EVENT_DETAILS_SUCCESS',
  GET_EVENT_DETAILS_FAILURE: 'events/GET_EVENT_DETAILS_FAILURE',
};
