
export const Types = {
  GET_RESTAURANT_DETAILS_REQUEST: 'restaurant/GET_RESTAURANT_DETAILS_REQUEST',
  GET_RESTAURANT_DETAILS_REQUEST_SUCCESS: 'restaurant/GET_RESTAURANT_DETAILS_REQUEST_SUCCESS',
  GET_RESTAURANT_DETAILS_REQUEST_FAILURE: 'restaurant/GET_RESTAURANT_DETAILS_REQUEST_FAILURE',
  RESET_DATA: 'restaurant/RESET_DATA',
};
