

export const Types = {
  ERROR_SERVER_CONNECTION: 'ERROR_SERVER_CONNECTION',
  YOU_MIGHT_LIKE_EMPTY: 'YOU_MIGHT_LIKE_EMPTY',
  SEARCH_NOT_FOUND: 'SEARCH_NOT_FOUND',
  INITIAL_SEARCH: 'INITIAL_SEARCH',
  POPULAR_EMPTY: 'POPULAR_EMPTY',
  SEARCH_EMPTY: 'SEARCH_EMPTY',
  BORING_CITY: 'BORING_CITY',
  HOME_EMPTY: 'HOME_EMPTY',
};
